#!/bin/bash
#SBATCH --job-name=ldsc_anno_jobs_human_NAc_NMF.txt
#SBATCH --output=./ldsc_anno_jobs_human_NAc_NMF.txt_err_out/jobs_%A_%a.out
#SBATCH --error=./ldsc_anno_jobs_human_NAc_NMF.txt_err_out/jobs_%A_%a.err
#SBATCH --partition=shared
#SBATCH --mem-per-cpu=5G --cpus-per-task=1
#SBATCH --array=1-73%73


echo "**** Job starts ****"
date
module load ldsc
perl job_batch.pl --jfile ldsc_anno_jobs_human_NAc_NMF.txt --nrun 20 --n $SLURM_ARRAY_TASK_ID
echo "**** Job ends ****"
date
