#!/bin/bash
#SBATCH --job-name=ldsc_anno_jobs_snRNAseq.txt
#SBATCH --output=./ldsc_anno_jobs_snRNAseq.txt_err_out/jobs_%A_%a.out
#SBATCH --error=./ldsc_anno_jobs_snRNAseq.txt_err_out/jobs_%A_%a.err
#SBATCH --partition=shared
#SBATCH --mem-per-cpu=5G --cpus-per-task=1
#SBATCH --array=1-22%22


echo "**** Job starts ****"
date
module load ldsc/1.0.1
perl job_batch.pl --jfile ldsc_anno_jobs_snRNAseq.txt --nrun 20 --n $SLURM_ARRAY_TASK_ID
echo "**** Job ends ****"
date
